version: "3.4"
services:
  database:
    image: tavaresrick/postgres:1.0
    deploy:
      mode: replicated
      replicas: 1

  backend:
    image: tavaresrick/twitter-collector-backend:$TAG
    ports:
      - "9000:8000"
    depends_on:
      - database
    environment:
      - TWITTER_CONSUMER_KEY=$TW_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET=$TW_CONSUMER_SECRET
      - TWITTER_ACCESS_SECRET=$TW_ACCESS_SECRET
      - TWITTER_APP_ACCESS_TOKEN=$TW_ACCESS_TOKEN
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=twitter-collector
      - DB_PASS=twitter
      - DB_NAME=twitter-collector
    deploy:
      mode: replicated
      replicas: 1